version: "3"
services:
  api: # <= dokecr compose exec {{api}} bash
    container_name: "python-service"
    env_file: .env.stg # 環境変数読み込み

    # setting on build
    build:
      context: .
      dockerfile: Dockerfile

    # File copy
    volumes:
      - ./src:/src
    working_dir: "/src"

    # other
    restart: always # 停止した際に自動で復活
    tty: true
